site_name: Titan Compiler Project
repo_url: https://github.com/titan-compiler-project/titan
repo_name: titan-compiler-project/titan

theme:
  name: "material"
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          filters: None
- search
- git-revision-date-localized:
    enable_creation_date: false
    fallback_to_build_date: true
    type: timeago
- mkdoxy:
    projects:
      TitanComms:
        src-dirs: titan/comms
        full-doc: True
        # template-dir: templates-custom
        # Example of custom template: https://mkdoxy-demo.kubaandrysek.cz/esp/annotated/
        doxy-cfg:
          FILE_PATTERNS: "*.cpp *.h*"
          RECURSIVE: True

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr
  - attr_list
  - pymdownx.snippets
    #  auto_append:
      #  - includes/abbreviations.md
  - md_in_html

extra_css:
  - extra/card_grid.css

nav:
  - Concept: "concept.md"
    # - "Introduction": "concept/intro.md"
  - User Guide:
    - "Getting Started": "user-guide/getting-started.md"
    - "Command Line Options Reference": "user-guide/cli-options.md"
    - "Compiler":
      - "Introduction" : "user-guide/compiler/intro.md"
      - "Python to SPIR-V" : "user-guide/compiler/python-spirv.md"
      - "SPIR-V to SystemVerilog" : "user-guide/compiler/spirv-systemverilog.md"
    - "Communications": "user-guide/comms.md"
    - "Synthesised Modules": "user-guide/synthesised-modules.md"
  - Reference Docs:
    - "Compiler":
      - "common":
        - "errors.py": "reference-docs/compiler/common/errors.md"
        - "grammar.py": "reference-docs/compiler/common/grammar.md"
        - "options.py": "reference-docs/compiler/common/options.md"
        - "symbols.py": "reference-docs/compiler/common/symbols.md"
        - "type.py": "reference-docs/compiler/common/type.md"
      - "compiler":
        - "helper.py": "reference-docs/compiler/compiler/helper.md"
        - "hinting.py": "reference-docs/compiler/compiler/hinting.md"
        - "node.py": "reference-docs/compiler/compiler/node.md"
        - "spirv.py": "reference-docs/compiler/compiler/spirv.md"
        - "verilog.py": "reference-docs/compiler/compiler/verilog.md"
      - "main.py" : "reference-docs/compiler/main.md"

    - "Comms Library":
      - "TitanComms.cpp" : "reference-docs/library/TitanComms.cpp.md"
    - "FPGA Shield": "reference-docs/pcb.md"
  - About: "about.md"
  - License: "license.md"
