// generated by titan, dont modify anything otherwise it might break =)
module add_2 (
	input wire clock,
	input logic [31:0] a,
	input logic [31:0] b,
	output wire [31:0] c
);
	logic [31:0] titan_id_0;
	always_ff @ (posedge clock) begin
		titan_id_0 <= a + b;
	end
	assign c = titan_id_0;
endmodule
